---
- name: Set up the blade group
  block:
    - name: Create the blade group
      ansible.builtin.group:
        name: "{{ blade_user }}-group"
        state: present
    - name: Add the blade user to the blade group
      ansible.builtin.user:
        name: "{{ blade_user }}"
        groups: "{{ blade_user }}-group"
        comment: Blade Application user

- name: Create blade folders
  block:
    - name: Create folder for blade data
      ansible.builtin.file:
        path: "{{ blade_home_dir }}"
        state: directory
        owner: "{{ blade_user }}"
        group: "{{ blade_user }}-group"
        mode: '0750'
    - name: Create folder for blade configs
      ansible.builtin.file:
        path: /etc/blade
        state: directory
        mode: '0700'
        owner: "{{ blade_user }}"
        group: "{{ blade_user }}-group"

- name: Produce blade node lists
  block:
    - name: Produce blade fullnode list
      ansible.builtin.template:
        src: fullnodelist.txt
        dest: /etc/blade/fullnodelist.txt
        mode: '0700'
    - name: Produce blade validator list
      ansible.builtin.template:
        src: validatorlist.txt
        dest: /etc/blade/validatorlist.txt
        mode: '0700'

- name: Config socket
  ansible.builtin.include_tasks: config-socket.yml
  when: config_socket

- name: Build blade binary
  block:
    - name: Install go
      ansible.builtin.include_tasks: go.yml
    - name: Build blade from source
      ansible.builtin.include_tasks: build-blade.yml

- name: Bootstrap blade
  ansible.builtin.include_tasks: bootstrap-blade.yml
  when: not restore_data

- name: Restore data
  ansible.builtin.include_tasks: restore-data.yml
  when: restore_data

- name: Create blade service file
  ansible.builtin.template:
    src: blade.service
    dest: /etc/systemd/system/blade.service
    mode: '0644'
  notify:
    - Restart Blade Service

- name: Restart Blade Service
  ansible.builtin.systemd:
    state: started
    name: blade
    enabled: true
