version: '3.8'
services:
  blade:
    container_name: blade
    image: b4n3/blade:latest
    user: blade
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - /var/lib/blade/bootstrap:/blade
    # entrypoint: [ ]