---
clean_deploy_title: devnet

#### Genesis Flags ###
block_gas_limit: 200_000_000
block_time: 2
gossip_msg_size: 1_048_576
json_rpc_batch_request_limit: 999
log_level: INFO
chain_id: 100

### Blade Service Flags ###
max_slots: 276480
max_enqueued: 276480

### Version Flags ###
polycli_tag: 0.1.30 # https://github.com/maticnetwork/polygon-cli/releases
blade_tag: feature/apex-bridge
cardano_tag: 8.9.2
apex_bridge_tag: main
geth_tag: v1.12.0
go_tag: 1.21.6.linux-amd64
## If the L1 is NOT an unlocked test account, then you'll need some wallet
# for funding validators. The address and private key here are used for this purpose
rootchain_coinbase_address: "0xREPLACE_WITH_ETH_ADDRESS"
rootchain_coinbase_private_key: "REPLACE_WITH_PRIVATE_KEY"

### NATIVE TOKEN ###
native_token_config: "Blade:BLADE:18:true"
is_bridge_active: false
is_london_fork_active: true

### Infra/Ansible Flags ###
ansible_ssh_private_key_file: ~/private.key
ansible_ssh_common_args: >
  -o IdentitiesOnly=yes
  -o StrictHostKeyChecking=no
  -o ProxyCommand="sh -c \"aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'\""
ansible_user: ubuntu
ansible_become: true
ansible_ssh_retries: 5

deployment_name: "{{ clean_deploy_title }}"
base_dn: "{{ deployment_name }}.blade.ethernal.private"
node_name: "{{ hostvars[inventory_hostname].tags.Hostname }}"
blade_domain: "{{ base_dn }}"
node_hostname: "{{ node_name }}.{{ blade_domain }}"

### Blade Flags ###
blade_repository: Ethernal-Tech/blade
blade_grpc_port: 10000
blade_p2p_port: 10001
blade_jsonrpc_port: 10002
blade_prometheus_port: 9091
node_exporter_port: 9092
node_exporter_web_listen_address: 127.0.0.1:{{ node_exporter_port }}
haproxy_port: 10222
blade_home_dir: /var/lib/blade
blade_user: blade
restore_data: false
s3_bucket: "" # AWS S3 Bucket name
loadtest_account: "0x85da99c8a7c2c95964c8efd687e95e632fc533d6"

### GitHub credential ###
## This need to access private repositories ##
gh_user: ""
gh_pat: ""

### Cardano Flags ###
cardano_chains:
  - vector
  - prime

### Apex Flags ###
apex_bridge_repository: Ethernal-Tech/apex-bridge
apex_bridge_home_dir: /var/lib/apex-bridge
apex_bridge_api_port: 10003
apex_user: apex

### Disk Flags ###
## This is the configuration related to mounting a separate device
storage_device_name: nvme1n1
storage_device_location: /dev/{{ storage_device_name }}
storage_mount_point: "{{ blade_home_dir }}"
storage_partition_name: State Data

### Local Geth Flags ###
geth_http_port: 8545
geth_miner_mnemonic: code code code code code code code code code code code quality
geth_chain_id: 1001
geth_p2p_port: 30303
