---
- name: Create dir for logs
  ansible.builtin.shell: |
    mkdir /opt/logs

- name: Get files from validator-001
  ansible.builtin.shell: |
    cp /var/lib/blade/bootstrap/nightly.blade.ethernal.private.tar.gz /opt/logs/
    cp /var/lib/blade/bootstrap_output.txt /opt/logs/
    cp /var/lib/blade/init.sh /opt/logs/
    cp /var/lib/blade/rootchain-wallet.json /opt/logs/
    cp /var/log/syslog /opt/logs/
    cd /opt/logs/ && zip -rq {{ hostvars[inventory_hostname].tags["Hostname"] }}.zip *
  when: hostvars[inventory_hostname].tags["Hostname"] == "validator-001"

- name: Get files from other hosts
  ansible.builtin.shell: |
    cp /var/log/syslog /opt/logs/
    cp /var/lib/geth/geth/nodekey /opt/logs/
    cd /opt/logs/ && zip -rq {{ hostvars[inventory_hostname].tags["Hostname"] }}.zip *
  when: hostvars[inventory_hostname].tags["Hostname"] != "validator-001"

- name: Get current datetime
  ansible.builtin.shell: "date +%Y-%m-%d-%H-%M"
  register: current_datetime

- name: Upload logs
  ansible.builtin.shell: |
    cd /opt/logs && aws s3 cp {{ hostvars[inventory_hostname].tags["Hostname"] }}.zip s3://blade-terraform-states/logs/{{ current_datetime.stdout }}/
