---
- name: Store all logs in /opt/logs
  ansible.builtin.shell: |
    cd /opt && mkdir logs
    cp /var/lib/blade/bootstrap/nightly.blade.ethernal.private.tar.gz logs/
    cp /var/lib/blade/bootstrap_output.txt logs/
    cp /var/lib/blade/genesis.json logs/
    cp /var/lib/blade/init.sh logs/
    cp /var/lib/blade/rootchain-wallet.json logs/
    cp /var/log/syslog logs/
    cp /var/lib/geth/geth/nodekey logs/
    cd logs && zip -rq {{ hostvars[inventory_hostname].tags["Hostname"] }}.zip *

- name: Get current datetime
  ansible.builtin.shell: "date +%Y-%m-%d-%H-%M"
  register: current_datetime

- name: Upload logs
  ansible.builtin.shell: |
    cd /opt/logs && aws s3 cp {{ hostvars[inventory_hostname].tags["Hostname"] }}.zip s3://blade-terraform-states/logs/{{ current_datetime.stdout }}/
