version: '3.8'
services:
  geth:
    container_name: geth
    image: etherium/client-go:latest
    user: geth
    restart: unless-stopped
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - /var/lib/geth:/root