- name: Wait for all hosts to be reachable
  hosts: all:!adot
  become: true
  gather_facts: false
  tags:
    - always
  tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:

- name: Gather facts
  hosts: all:!adot
  become: true
  tags:
    - always
  tasks:
    - name: Gather facts
      ansible.builtin.gather_facts:
      retries: 10
      delay: 10
      register: result
      until: result is not failed

- name: Provision servers and configure monitoring
  hosts: all:!adot
  become: true
  tags:
    - init
  roles:
    - common

- name: Provision rootchain server
  hosts: geth
  become: true
  tags:
    - geth
  roles:
    - rootchain-server

- name: Provision blade
  hosts: fullnode:validator
  become: true
  tags:
    - blade
  roles:
    - mounted-storage
    - blade

- name: Configure monitoring (node-exporter)
  hosts: all:!adot
  become: true
  tags:
    - metrics
  roles:
    - node-exporter

- name: Provision explorer
  hosts: explorer
  become: true
  tags:
    - explorer
  roles:
    - explorer

- name: Provision faucet
  hosts: explorer
  become: true
  tags:
    - faucet
  roles:
    - faucet

- name: Install logrotate
  hosts: all:!adot
  become: true
  tags:
    - logrotate
  roles:
    - logrotate
