- hosts: fullnode:validator
  become: true
  tasks:
    - name: Stop Blade service
      ansible.builtin.systemd:
        state: stopped
        name: blade
        enabled: false
    - name: Pause for 1 minute to make sure Blade service is stopped
      ansible.builtin.pause:
        minutes: 1

- hosts: validator_001
  become: true
  tags:
    - upload-data
  roles:
    - upload-data
